SELECT job_id , COUNT(*)
FROM employees
GROUP BY JOB_ID;

#SHOW EVERY JOBS HIGHTEST SALARY

SELECT JOB_ID, MAX(SALARY)
FROM employees
GROUP BY job_id;

SELECT JOB_ID , COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING COUNT(*) >1;